Don't require Function#bind polyfill to work, fixes #57
Fixes:
TypeError: 'undefined' is not a function (evaluating 'this.checkUrl.bind(this)')
https://github.com/chaplinjs/chaplin/issues/757